databases:
  - name: mysite
    databaseName: mysite
    users: mysite
    plans: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plans: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startComand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabases:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync:false- key: WEB_CONCURRENCY
        value: 2